# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

version: '3.7'

services:
  pman:
    image: fnndsc/pman
    # Since pman spins off containers of its own it needs to mount storeBase dir (where
    # pfcon shares the data) into the spawned container. This directory is passed in the
    # STOREBASE env variable.
    environment:
      - STOREBASE
      - CONTAINER_ENV=swarm
    env_file:
      - secrets/.pman.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "30010:30010"
    command: ["gunicorn", "-w", "5", "-b", "0.0.0.0:30010", "-t",  "200", "pman.wsgi:application"]
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - remote
    labels:
      name: "pman"
      role: "pman service"

networks:
  remote:
