#!/usr/bin/env bash

source ./decorate.sh

title -d 1 "Destroying pman containerized development environment" "from ./docker-compose.yml"
windowBottom

title -d 1 "Stopping services..."
    docker-compose stop
windowBottom

title -d 1 "Removing all containers..."
    docker-compose rm -vf 
windowBottom

title -d 1 "Removing any orphans..."
    a_VOLS=(
        "pman"
    )
    a_PVOLS=()
    for vol in ${a_VOLS[@]}; do
        SCANTXT=$(printf "Scanning for '%s'... " "$vol")
        printf "%50s" "$SCANTXT"
        DOCKERPS=$(docker ps -a | grep -v CONTAINER | grep $vol)
        DOCKERVOLNAME=$(echo $DOCKERPS | awk '{print $2}')
        DOCKERID=$(echo $DOCKERPS | awk '{print $1}')
        if (( ${#DOCKERVOLNAME} )); then
            printf "${Yellow}[ %s ]${NC}\n" "$DOCKERID:$DOCKERVOLNAME"
        else
            printf "${Green}[ Not orphaned. ]${NC}\n"
        fi
        a_PVOLS+=($DOCKERID)
    done
    printf "\n"
    for VOL in ${a_PVOLS[@]} ; do 
        printf "${Cyan}Removing ${Yellow}[ $VOL ]${Cyan}${NC}\n"
        docker stop $VOL >/dev/null && docker rm -vf $VOL > /dev/null
    done
windowBottom
