#!/usr/bin/env bash

G_CONTAINER="fnndsc/pman"

G_SYNOPSIS="

    NAME

        pfioh

    SYNOPSIS

        pfioh           [-c <container>]                                \\
                        [... cmd line parameters to contained phioh ]

    ARGS

        [-c <container>]
        An optional container to use. If not specified, will assume 'fnndsc/pman'.

    DESCRIPTION

        'pfioh' is a helper script that starts a dockerized instance
        of 'pfioh' from the fnndsc/pman container (note that the
        actual container can be overridden with a '-c <container>'
        specification).

        Any additional command line parameters are passed unchanged to the
        container entrypoint.

"

TEMP=$(getopt -q -o c: -n 'parse-options' -- "$@")

while true; do
    case "$1"
    in
        -c)  shift ; G_CONTAINER=$1 ; shift ;;
        --) shift ; break ;;
        *) break ;;
    esac
done

shift $(($OPTIND - 1))
PFIOHARGS=$*

CMD="docker run --name pfioh -p 5055:5055 -v /home:/Users --rm -ti $G_CONTAINER pfioh $PFIOHARGS"
echo "$CMD"
eval $CMD
