#!/usr/bin/env bash

G_CONTAINER="fnndsc/pman"

G_SYNOPSIS="

    NAME

        dk_pman

    SYNOPSIS

        dk_pman         [-d <container>]                                \\
                        [... cmd line parameters to contained pman ]

    DESCRIPTION

        'dk_pman' is a helper script that starts a dockerized instance
        of 'pman' from (by default) the fnndsc/pman container (this can
        be overridden by a '-d <container>' specification.

        Any additional command line parameters are passed unchanged to the
        container entrypoint.

"

TEMP=$(getopt -q -o c: -n 'parse-options' -- "$@")

while true; do
    case "$1"
    in
        -c)  shift ; G_CONTAINER=$1 ; shift ;;
        --) shift ; break ;;
        *) break ;;
    esac
done

shift $(($OPTIND - 1))
PMANARGS=$*

CMD="docker run --name pman -v /home:/Users --rm -ti $G_CONTAINER pman $PMANARGS"
eval $CMD

