#!/usr/bin/env bash

G_CONTAINER="fnndsc/pman"

G_SYNOPSIS="

    NAME

        pman

    SYNOPSIS

        pman            [-c <container>]                                \\
                        [... cmd line parameters to contained pman ]

    DESCRIPTION

        'pman' is a helper script that starts a dockerized instance
        of 'pman' from the fnndsc/pman container (note that the
        actual container can be overridden by a '-c <container>'
        specification).

        Any additional command line parameters are passed unchanged to the
        container entrypoint.
"

TEMP=$(getopt -q -o c: -n 'parse-options' -- "$@")

while true; do
    case "$1"
    in
        -c)  shift ; G_CONTAINER=$1 ; shift ;;
        --) shift ; break ;;
        *) break ;;
    esac
done

shift $(($OPTIND - 1))
PMANARGS=$*

CMD="docker run --name pman -v /home:/Users --rm -ti $G_CONTAINER pman $PMANARGS"
eval $CMD

