apiVersion: v1
kind: Service
metadata:
  name: pman
  labels:
    app: pman
    env: production
spec:
  type: NodePort
  selector:
    app: pman
    env: production
  ports:
    - port: 30010
      targetPort: 30010
      nodePort: 30010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pman
  labels:
    app: pman
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pman
      env: production
  template:
    metadata:
      name: pman
      labels:
        app: pman
        env: production
    spec:
      containers:
        - image: fnndsc/pman
          name: pman
          ports:
            - containerPort: 30010
          command: ["gunicorn"]
          args: ["-w", "5", "-b", "0.0.0.0:30010", "-t",  "200", "pman.wsgi:application"]
          # Since pman spins off containers of its own it needs to mount storeBase dir
          # (where pfcon shares the data) into the spawned container. This directory is
          # passed in the STOREBASE env variable.
          env:
            - name: STORAGE_TYPE
              value: ${STORAGE_TYPE}
            - name: NFS_SERVER
              value: ${NFS_SERVER}
            - name: STOREBASE
              value: ${STOREBASE}
            - name: CONTAINER_ENV
              value: kubernetes
            - name: JOB_NAMESPACE
              value: ${NAMESPACE}
          envFrom:
            - configMapRef:
                name: pman-config
