apiVersion: v1
kind: Service
metadata:
  name: pman
  labels:
    app: pman
    env: development
spec:
  type: NodePort
  selector:
    app: pman
    env: development
  ports:
    - port: 30010
      targetPort: 30010
      nodePort: 30010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pman
  labels:
    app: pman
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pman
      env: development
  template:
    metadata:
      name: pman
      labels:
        app: pman
        env: development
    spec:
      # During dev pman needs access to the pfcon storeBase folder (and hence the volume)
      # mapping from the HOST file system space to be able to run the tests. This is not
      # necessary for a production pman.
      #
      # Since pman spins off containers of its own it needs to mount storeBase dir (where
      # pfcon shares the data) into the spawned container. This directory is passed in the
      # STOREBASE env variable.
      containers:
        - image: fnndsc/pman:dev
          name: pman
          stdin: true
          tty: true
          ports:
            - containerPort: 30010
          env:
            - name: APPLICATION_MODE
              value: development
            - name: STOREBASE
              value: ${STOREBASE}
            - name: CONTAINER_ENV
              value: kubernetes
          command: ["pman"]
          args: ["--ip", "0.0.0.0", "--port", "30010", "--verbosity", "1"]
          volumeMounts:
            - mountPath: "/home/localuser/storeBase"
              name: "store-base"
            - mountPath: "/home/localuser/pman/pman"
              name: "pman-source"
            - mountPath: "/home/localuser/pman/bin"
              name: "pman-bin"
            - mountPath: "/home/localuser/pman/tests"
              name: "pman-tests"
      volumes:
        - name: "store-base"
          hostPath:
            path: ${STOREBASE}
        - name: "pman-source"
          hostPath:
            path: ${SOURCEDIR}/pman
        - name: "pman-bin"
          hostPath:
            path: ${SOURCEDIR}/bin
        - name: "pman-tests"
          hostPath:
            path: ${SOURCEDIR}/tests
