apiVersion: v1
kind: Service
metadata:
  name: pman
  labels:
    app: pman
    env: development
spec:
  type: NodePort
  selector:
    app: pman
    env: development
  ports:
    - port: 5005
      targetPort: 5005
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pman
  labels:
    app: pman
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pman
      env: development
  template:
    metadata:
      name: pman
      labels:
        app: pman
        env: development
    spec:
      serviceAccountName: job-creator
      containers:
        - name: pfcon
          image: ghcr.io/fnndsc/pfcon:5.0.0
          ports:
            - name: pfcon
              containerPort: 5005
          env:
            - name: COMPUTE_SERVICE_URL
              value: http://localhost:5010/api/v1/
            - name: SECRET_KEY
              value: secret
            - name: PFCON_USER
              value: pfcon
            - name: PFCON_PASSWORD
              value: pfcon1234
          volumeMounts:
            - mountPath: /var/local/storeBase
              name: storebase

        - name: pman
          image: localhost:5001/fnndsc/pman:latest
          imagePullPolicy: Always
          env:
            - name: SECRET_KEY
              value: secret
            - name: CONTAINER_ENV
              value: kubernetes
            - name: STORAGE_TYPE
              value: kubernetes_pvc
            - name: VOLUME_NAME
              value: storebase

      volumes:
        - name: storebase
          persistentVolumeClaim:
            claimName: storebase


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storebase
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # CHANGE ME if not using kind
  resources:
    requests:
      storage: 20Gi
